apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sif-debug-app
  namespace: dusseldorf
  labels:
    team: dusseldorf
spec:
  image: docker.pkg.github.com/nais/testapp/testapp:latest
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: {{resources.limits.cpu}}
      memory: {{resources.limits.memory}}
    requests:
      cpu: {{resources.requests.cpu}}
      memory: {{resources.requests.memory}}
  env:
    - name: BIGQUERY_NAME
      value: mybqdataset
{{#each envs}}
    - name: "{{name}}"
      value: "{{value}}"
{{/each}}
